### ISSUE TITLE
Nb-layout-header causing ng test to fail

### ISSUE THREAD

**Issue by DawsonLey** [akveo/nebular#2214]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
This bug only appears while testing, and only in components which contain the nb header component. The app works fine, it's purely an error I get while testing. 

**Expected behavior:**
The test would pass (as the app works fine, this seems logical, and all other nb-layout tags work fine)

**Steps to reproduce:**
Use nb-layout-header in any component, ng test, errors out. To be clear, I am familiar with angular spec files, this app has lots of tests, all of which work fine, I know how to import modules, etc.

**Related code:**
```<nb-layout-header></nb-layout-header>```

A sample application via GitHub

StackBlitz [StackBlitz Seed Project](https://stackblitz.com/github/akveo/nebular-seed)

-->

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node v10.15.0` and `npm 6.4.1`
OS: Mac0S Mojave
Browser: Chrome
-->
```

**Angular, Nebular**
```
{
  "name": "service-planning-front-end",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@nebular/auth": "^4.5.0",
    "@nebular/eva-icons": "^4.6.0",
    "@nebular/theme": "^4.5.0",
    "@ngrx/effects": "^8.5.2",
    "@ngrx/schematics": "^8.5.2",
    "@ngrx/store": "^8.0.0",
    "@sentry/browser": "^5.11.1",
    "eva-icons": "^1.1.1",
    "husky": "^3.1.0",
    "moment": "^2.24.0",
    "moment-fquarter": "^1.0.0",
    "moment-range": "^4.0.2",
    "ngx-drag-to-select": "^3.1.1",
    "precise-commits": "^1.0.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "precise-commits"
    }
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@schematics/angular": "^8.3.23",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "prettier": "1.19.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

```

**Comment by pjmagee** [comment]
I seem to be having the same issue...

Hi, we've just started writing our own starting template based off the nebular library, we're integrating ngrx into our starting project structure, and added a basic spec for a user welcome component, which uses the `nb-layout-header` component. 

Do you have an example ng test you could share, or potentially other examples as we can find any in the existing ngx-admin templates?

This is what i have so far as an example:

```

@Component({
    selector: 'app-user-header',
    template: `
      <nb-layout-header subheader>
        <div *ngIf="$userState | async as userState">
            <ng-template [ngIf]="userState.authenticated">
                Hello, <b>{{ userState.userName }}</b>!
            </ng-template>
            <ng-template [ngIf]="!userState.authenticated">
                Welcome to XpertHR Reward, please login.
            </ng-template>
        </div>
      </nb-layout-header>
    `
})
export class UserHeaderComponent {

    $userState: Observable<UserState>;

    constructor(public store: Store<AppState>) {
        this.$userState = store.select(s => s.user);
    }
}
```

The associated spec:

```

describe('UserHeaderComponent', () => {

  let fixture: ComponentFixture<UserHeaderComponent>;
  let store: MockStore<AppState>;
  let userState: UserState = { userName: '', authenticated: false, email: '', roles: [] }

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        // Why is this failing?
        RouterTestingModule.withRoutes([]), NbThemeModule.forRoot(), NbLayoutModule
      ],
      providers: [
        provideMockStore({ initialState: { user: userState } })
      ],
      declarations: [UserHeaderComponent]
    });

    fixture = TestBed.createComponent<UserHeaderComponent>(UserHeaderComponent);
    store = TestBed.get<Store<AppState>>(Store);
    fixture.detectChanges();

  });

  // https://ngrx.io/guide/store/testing#using-mock-selectors

  it('it should say please login', () => {
    expect(fixture.debugElement.queryAll(By.css('div'))[0].nativeElement.textContent).toBe('Welcome to XpertHR Reward, please login.');
  });

  it('it should greet the user with hello when logged in', () => {

    store.setState({ user: { userName: 'Patrick', authenticated: true, email: '', roles: [] } });

    store.refreshState();
    fixture.detectChanges();

    expect(fixture.debugElement.queryAll(By.css('div'))[0].nativeElement.textContent)
      .toBe('Welcome to XpertHR Reward, please login.');

  });

});
```

output from ng test

```
Chrome 79.0.3945 (Windows 10.0.0): Executed 2 of 2 (2 FAILED) (0 secs / 0.343 secs)
Chrome 79.0.3945 (Windows 10.0.0) UserHeaderComponent it should say please login FAILED
        NullInjectorError: StaticInjectorError(DynamicTestModule)[NbLayoutHeaderComponent -> NbLayoutComponent]:
          StaticInjectorError(Platform: core)[NbLayoutHeaderComponent -> NbLayoutComponent]:
            NullInjectorError: No provider for NbLayoutComponent!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'NbLayoutHeaderComponent', Function ], ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 50511889, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 16957457, directChildFlags: 16826369, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 4, bindings: [ Object({ flags: 2, ns: '', name: 'fixed', nonMinifiedName: 'fixed', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'subheader', nonMinifiedName: 'subheader', securityContext: undefined, suffix: undefined }) ], bindingFlags: 2, outputs: [  ], element: Object({ ns: '', name: 'nb-layout-header', attrs: [ Array ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circul ...
            at <Jasmine>
            at NullInjector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1354:1)
            at resolveToken (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1681:1)
            at tryResolveToken (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1607:1)
            at StaticInjector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1470:1)
            at resolveToken (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1681:1)
            at tryResolveToken (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1607:1)
            at StaticInjector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:1470:1)
            at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:23104:1)
            at NgModuleRef_.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:24192:1)
            at resolveDep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:24722:1)
        TypeError: Cannot read property 'debugElement' of undefined
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/components/user-header/user-header.component.spec.ts:38:20)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:359:1)
            at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:308:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:358:1)
            at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:124:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:561:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:576:1)
Chrome 79.0.3945 (Windows 10.0.0): Executed 2 of 2 (2 FAILED) (0.364 secs / 0.343 secs)
TOTAL: 2 FAILED, 0 SUCCESS
```


```

**Comment by DawsonLey** [comment]
Your output from ng test looks the same as mine except im on mac

```NullInjectorError: StaticInjectorError(DynamicTestModule)[NbLayoutHeaderComponent -> NbLayoutComponent]:
          StaticInjectorError(Platform: core)[NbLayoutHeaderComponent -> NbLayoutComponent]:
            NullInjectorError: No provider for NbLayoutComponent!``` that's the one

**Comment by JonasPetry** [comment]
Can confirm this error!
