### ISSUE TITLE
Nebular 5.0.0-beta-8 production build error on Angular 8.

### ISSUE THREAD

**Issue by GreedyA1** [akveo/nebular#2257]
### Issue type

* [ x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
ng serve is working great.
on ng build --prod I don't get any errors but when I open the production webpage or docker I see error: 

```
main-es2015.5c32b2c62f8882e2ccb1.js:1 Uncaught NullInjectorError: StaticInjectorError(s)[a -> t]: 
  StaticInjectorError(Platform: core)[a -> t]: 
    NullInjectorError: No provider for t!
    at L.get (http://mypage.commain-es2015.5c32b2c62f8882e2ccb1.js:1:628328)
    at http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:645764
    at t (http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:646144)
    at Be.get (http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:646295)
    at http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:645764
    at t (http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:646144)
    at Be.get (http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:646295)
    at Ur (http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:669629)
    at http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:669808
    at qr (http://mypage.com/main-es2015.5c32b2c62f8882e2ccb1.js:1:670002)
```

**Expected behavior:**
on ng build --prod ther should be no error

**Steps to reproduce:**

change existing package json 

from

```
    "@nebular/date-fns": "^4.6.0",
    "@nebular/eva-icons": "^4.6.0",
    "@nebular/theme": "^4.6.0",
```

to

```
    "@nebular/date-fns": "^5.0.0-beta.8",
    "@nebular/eva-icons": "^5.0.0-beta.8",
    "@nebular/theme": "^5.0.0-beta.8",
```

**Related code:**

couldn't reproduce error on stackblitz since it only appears after ng build --prod and deployed on docker or server

### Other information:

```
npm: 6.12.0
Node: v12.13.0
OS: Windows 10
Browser: Chrom
```

**Angular, Nebular**
```
Angular 8.8.3
Nebular 4.6.0 to 5.0.0-beta.8
```

**Comment by GreedyA1** [comment]
I just ran the same project in ng serve --prod and got more detailed error.

`Uncaught NullInjectorError: StaticInjectorError(AppModule)[NbEvaIconsModule -> NbIconLibraries]: 
  StaticInjectorError(Platform: core)[NbEvaIconsModule -> NbIconLibraries]: 
    NullInjectorError: No provider for NbIconLibraries!
    at NullInjector.get (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1064603)
    at http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1095792
    at tryResolveToken (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1096472)
    at StaticInjector.get (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1096689)
    at http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1095792
    at tryResolveToken (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1096472)
    at StaticInjector.get (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1096689)
    at resolveNgModuleDep (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1135565)
    at http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1135884
    at _createProviderInstance (http://localhost:4200/main.7da66c0fabd0192657e0.js:1:1136297)`

**Comment by GreedyA1** [comment]
As I found out nebular 5 only works with angular 9+. after updating to angular 9 everything works.
