### ISSUE TITLE
Bug: Cant use nebular/auth without providing nebular/theme

### ISSUE THREAD

**Issue by sayax** [akveo/nebular#2496]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [+ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Importing only nebular/auth causes an issue 
NullInjectorError: R3InjectorError(AppBrowserModule)[EffectsFeatureModule -> InjectionToken ngrx/effects: Feature Effects -> [object Object] -> AuthEffects -> AuthDataAccessService -> InjectionToken Nebular Auth Strategies -> NbOAuth2AuthStrategy -> InjectionToken Window -> InjectionToken Window -> InjectionToken Window]: 
  NullInjectorError: No provider for InjectionToken Window!

**Expected behavior:**

serving a project without nebular/theme without issue

**Steps to reproduce:**

1) create an angular 10 project
2) import NbAuthModule.forRoot()
3) start a project

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```
node version v14.3.0
npm 6.14.5
"@angular/core": "^10.0.4",
"@nebular/auth": "^6.0.0",
**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by wandyer** [comment]
I have the same problem, trying to use nebular auth/security with bootstrap, I don't want the nebular theme

The error I get when trying to run the project:

```
ERROR in The target entry-point "@nebular/auth" has missing dependencies:
 - @nebular/theme
```

**Comment by aesadaf** [comment]
same issue here can we use auth without ebular theme ?

**Comment by mrluzio** [comment]
Same here, it would be nice to be able to use auth without theme.

**Comment by timokluser-dev** [comment]
Is there any update on this issue? 
I was able to install the `@nebular/auth` without any dependency conflicts but it seems like that the `NB_WINDOW` is needed in order to work. Unfortunately the variable is only defined in the `@nebular/theme`. 
  
Is there a proper way to fix this?

**Comment by khashashin** [comment]
According to the docs it should be possible to use the `@nebular/auth` without `@nebular/theme`:

> **Install the module**
> First, let's install the module as it's distributed as npm package. Make sure you have the [Nebular Theme module up and running](https://akveo.github.io/nebulardocs/installation/add-into-existing-project). Nebular Theme is required to use built-in Auth Components. _**If you are not going to use those at all, you can use `Auth Module` without the `Nebular Theme` module.**_

But I get following error in the ng console:

```
ng serve
> ng.cmd run app:serve --host=localhost --port=8100
[ng] - Generating browser application bundles (phase: setup)...
[ng] H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
[ng]                 throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
[ng]                 ^
[ng] Error: The target entry-point "@nebular/auth" has missing dependencies:
[ng]  - @nebular/theme
[ng]     at TargetedEntryPointFinder.findEntryPoints (H:\Projects\p1\nohchiMott\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
[ng]     at H:\Projects\p1\nohchiMott\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41       
[ng]     at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
[ng]     at H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59    
[ng]     at SyncLocker.lock (H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
[ng]     at SingleProcessExecutorSync.execute (H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
[ng]     at Object.mainNgcc (H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
[ng]     at Object.process (H:\Projects\p1\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
[ng]     at NgccProcessor.processModule (H:\Projects\p1\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)  
[ng]     at H:\Projects\p1\node_modules\@ngtools\webpack\src\ivy\host.js:146:18

[ERROR] ng has unexpectedly closed (exit code 1).

        The Ionic CLI will exit. Please check any output above for error details.
```
