### ISSUE TITLE
NbTreeGrid Error NullInjectorError: No provider for InjectionToken CDK_TABLE!

### ISSUE THREAD

**Issue by darrenparkinson** [akveo/nebular#3241]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When adding `nbTreeGrid` to my component, I get this error:

`ERROR NullInjectorError: R3InjectorError(Standalone[_ProfileComponent])[InjectionToken CDK_TABLE -> InjectionToken CDK_TABLE -> InjectionToken CDK_TABLE -> InjectionToken CDK_TABLE]: 
  NullInjectorError: No provider for InjectionToken CDK_TABLE!`

**Expected behavior:**

I expect to not receive the error when following the installation information from the documentation here: https://akveo.github.io/nebular/docs/components/tree-grid/overview#nbtreegridcomponent

**Steps to reproduce:**

* Create a new component
* Add code as per the documentation (see below)
* Get the error

**Related code:**

```html
<nb-card status="info">
    <nb-card-body>
        <table [nbTreeGrid]="data" equalColumnsWidth>
        </table>
    </nb-card-body>
</nb-card>
```

With the following in the component:

```javascript
import { Component, Inject } from '@angular/core';
import { NbCardModule, NbTreeGridModule } from '@nebular/theme';

interface TreeNode<T> {
  data: T;
  children?: TreeNode<T>[];
  expanded?: boolean;
}

interface FSEntry {
  name: string;
  size: string;
  kind: string;
  items?: number;
}

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [NbCardModule, NbTreeGridModule],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.scss'
})
export class ProfileComponent {
  columns = ['item', 'value'];
  data: TreeNode<FSEntry>[] = []
  constructor() {}
}
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
Node v18.17.1
NPM v9.6.7
OS: MacOS Sonoma 14.1.1
Browser: Chrome
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
 "@angular/animations": "^17.1.0",
    "@angular/cdk": "^17.1.0",
    "@angular/common": "^17.1.0",
    "@angular/compiler": "^17.1.0",
    "@angular/core": "^17.1.0",
    "@angular/forms": "^17.1.0",
    "@angular/platform-browser": "^17.1.0",
    "@angular/platform-browser-dynamic": "^17.1.0",
    "@angular/router": "^17.1.0",
    "@nebular/eva-icons": "^13.0.0",
    "@nebular/security": "^13.0.0",
    "@nebular/theme": "^13.0.0",
    "bootstrap": "^5.3.2",
    "eva-icons": "^1.1.3",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
```

**Comment by Szafa99** [comment]
same problem

**Comment by HitkoDev** [comment]
It seems to be related to some changes introduced in https://github.com/angular/components/pull/28356, you can try to set `"@angular/cdk": "<17.1.0"` until a fix is provided.

**Comment by crodriguez6497** [comment]
Same issue

**Comment by robkrzn** [comment]
Same issue

**Comment by diegoarndt** [comment]
I am facing the exact same issue

**Comment by pazdernikpavel** [comment]
Same problem here..

**Comment by jeroenpol** [comment]
> It seems to be related to some changes introduced in [angular/components#28356](https://github.com/angular/components/pull/28356), you can try to set `"@angular/cdk": "<17.1.0"` until a fix is provided.

Remember that you also should override the dependency of @nebular/theme, otherwise Nebular will complain:

```
"@nebular/theme": {
      "@angular/cdk": "<17.1.0"
    }
```

**Comment by helberhlm** [comment]
Same problem here

**Comment by crodriguez6497** [comment]
Any update on this? Or perhaps any better alternative than setting @angular/cdk <17.1.0?

**Comment by mannynable** [comment]
Same issue :(

**Comment by theophane-girard** [comment]
any news ?

**Comment by lvlkoo** [comment]
Any updates on this?

**Comment by jkneepkens** [comment]
We still get the error `NullInjectorError: NullInjectorError: No provider for InjectionToken CDK_TABLE!` after upgrading Nebular to v14, is there already a fix available (otherwise then use the `"@angular/cdk": "<17.1.0"` fix)?

**Comment by basvandorst** [comment]
Issue still exists with latest Angular & Nebular version:

```
core.mjs:7372 ERROR
NullInjectorError: NullInjectorError: No provider for InjectionToken CDK_TABLE!
    at NullInjector.get (core.mjs:1659:27)
    at R3Injector.get (core.mjs:3105:33)
    at R3Injector.get (core.mjs:3105:33)
    at R3Injector.get (core.mjs:3105:33)
    at R3Injector.get (core.mjs:3105:33)
    at R3Injector.get (core.mjs:3105:33)
    at ChainedInjector.get (core.mjs:5447:36)
    at lookupTokenUsingModuleInjector (core.mjs:5800:39)
    at getOrCreateInjectable (core.mjs:5848:12)
    at ɵɵdirectiveInject (core.mjs:11915:19)
Show 22 more frames
```

Steps to reproduce:
- Check out this repo
- Go to: [Tree Grid Sortable](http://localhost:4200/#/tree-grid/tree-grid-sortable.component)

**Comment by Khalil-IT** [comment]
i still get the same error
<code>
Angular CLI: 17.3.8
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.8
@angular/google-maps            17.0.1
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
</code>
<code>
core.mjs:6531  ERROR NullInjectorError: R3InjectorError(_AppModule)[InjectionToken CDK_TABLE -> _NbTreeGridComponent -> _NbTreeGridComponent]: 
  NullInjectorError: No provider for _NbTreeGridComponent!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at injectInjectorOnly (core.mjs:1100:40)
    at ɵɵinject (core.mjs:1106:42)
    at Object.factory (core.mjs:3325:29)
    at core.mjs:3219:47
    at runInInjectorProfilerContext (core.mjs:866:9)
    at R3Injector.hydrate (core.mjs:3218:21)
    at R3Injector.get (core.mjs:3082:33)
</code>

**Comment by Khalil-IT** [comment]
@darrenparkinson

i want to ask if you sloved it or not

**Comment by flacohenao** [comment]
> > It seems to be related to some changes introduced in [angular/components#28356](https://github.com/angular/components/pull/28356), you can try to set `"@angular/cdk": "<17.1.0"` until a fix is provided.
> 
> Remember that you also should override the dependency of @nebular/theme, otherwise Nebular will complain:
> 
> ```
>   "overrides": {
>     "@nebular/theme": {
>       "@angular/cdk": "<17.1.0"
>     }
>   }
> ```

Hi @jeroenpol.. Sorry for this dumb question, but.. where should I override the nebular/theme dependency? package.json doesn't support this kind of things.. Am I wrong?

**Comment by jeroenpol** [comment]
> > > It seems to be related to some changes introduced in [angular/components#28356](https://github.com/angular/components/pull/28356), you can try to set `"@angular/cdk": "<17.1.0"` until a fix is provided.
> > 
> > 
> > Remember that you also should override the dependency of @nebular/theme, otherwise Nebular will complain:
> > ```
> >   "overrides": {
> >     "@nebular/theme": {
> >       "@angular/cdk": "<17.1.0"
> >     }
> >   }
> > ```
> 
> Hi @jeroenpol.. Sorry for this dumb question, but.. where should I override the nebular/theme dependency? package.json doesn't support this kind of things.. Am I wrong?

Hi!

`package.json` does support this. Check https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by flacohenao** [comment]
> > > > It seems to be related to some changes introduced in [angular/components#28356](https://github.com/angular/components/pull/28356), you can try to set `"@angular/cdk": "<17.1.0"` until a fix is provided.
> > > 
> > > 
> > > Remember that you also should override the dependency of @nebular/theme, otherwise Nebular will complain:
> > > ```
> > >   "overrides": {
> > >     "@nebular/theme": {
> > >       "@angular/cdk": "<17.1.0"
> > >     }
> > >   }
> > > ```
> > 
> > 
> > Hi @jeroenpol.. Sorry for this dumb question, but.. where should I override the nebular/theme dependency? package.json doesn't support this kind of things.. Am I wrong?
> 
> Hi!
> 
> `package.json` does support this. Check https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

Thanks @jeroenpol 

Even with the override, Tree component still not working :(

**Comment by flacohenao** [comment]
> We still get the error `NullInjectorError: NullInjectorError: No provider for InjectionToken CDK_TABLE!` after upgrading Nebular to v14, is there already a fix available (otherwise then use the `"@angular/cdk": "<17.1.0"` fix)?

The override wont work in anycase. I dont know if its just override the cdk or if we need to do anything else.

**Comment by OngWiYi** [comment]
any update on this?

**Comment by lvlkoo** [comment]
Any updates? Almost year passed since issue report

**Comment by Makentosha** [comment]
Looks like they won't fix it, 11 months since issue it's open

**Comment by crodriguez6497** [comment]
> Looks like they won't fix it, 11 months since issue it's open

https://github.com/akveo/nebular/issues/3213

They won't fix it. I switched to PrimeNG and never looked back.

**Comment by RowenLiu** [comment]
Resolved this issue !!! 
1.add overrides in package.json
  "overrides": {
    "@nebular/theme": {
      "@angular/cdk": "<17.1.0"
    }
  }

2.upgrade nebular to V14.0.2  to resolve this issue
3. add providers to component
@Component({
templateUrl: "xxx",
styleUrls: "xxx",
providers: [
    { provide: CDK_TABLE, useExisting: NbTreeGridComponent },
  ]
})
