### ISSUE TITLE
Issue with Expected Version

### ISSUE THREAD

**Issue by otahboub** [akveo/nebular#63]
Hi,

 I cloned the repo and performed npm install. When I attempted to run the the admin dashboard, I go the following error message:

ERROR in Error: Metadata version mismatch for module /Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/ng2-tree/index.d.ts, found version 4, expected 3, resolving symbol ComponentsModule in /Users/omar_tahboub/akveo-ngx-admin/ngx-admin/src/app/pages/components/components.module.ts, resolving symbol ComponentsModule in /Users/omar_tahboub/akveo-ngx-admin/ngx-admin/src/app/pages/components/components.module.ts
    at Error (native)
    at syntaxError (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at includeLazyRouteAndSubRoutes (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:66:25)
    at Array.reduce (native)
    at includeLazyRouteAndSubRoutes (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:67:26)
    at Array.reduce (native)
    at Object.listLazyRoutesOfModule (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:54:36)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/omar_tahboub/akveo-ngx-admin/ngx-admin/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Any help is highly appreciated ! 

Omar

**Comment by Tibing** [comment]
Hi, @otahboub!

Could you please try to run it with *npm 5+*?

**Comment by nnixaa** [comment]
This is an npm version issue, please use the required version. Thanks!
