### ISSUE TITLE
Error in production build

### ISSUE THREAD

**Issue by arabbani** [akveo/nebular#739]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description
I'm using v2.0.0-rc.10. The production build is producing the following error: 
**Current behavior:**

```
[ERROR] Error: Parse error on line 1:                                                                                                                                   
[ERROR] (* 1.25) + 4px  
```   
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
npm: v6.4.1
node: v8.12.0
OS: Windows 10
Browser: Chrome
```

**Angular, Nebular**
```
Angular : 6.1.0
Nebular: v2.0.0-rc.10
```

**Comment by Tibing** [comment]
Hi @arabbani, could you please provide the reproducible example?

**Comment by arabbani** [comment]
Steps to reproduce:
 I'm using Nebular with JHipster v5.3.4.
1. Create a jhipster project
2. Integrate Nebular.
3. Build for production

Following the complete error log:

```
[ERROR] Error: Parse error on line 1:
[ERROR] (* 1.25) + 4px
[ERROR] Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 
'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 
'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'MUL'
[ERROR]     at Parser.parseError (D:\Projects\arif\fb- 
quiz\node_modules\cssnano-preset-default\node_modules\reduce-css- 
calc\dist\parser.js:160:21)
[ERROR]     at Parser.parse (D:\Projects\arif\fb-quiz\node_modules\cssnano- 
preset-default\node_modules\reduce-css-calc\dist\parser.js:226:22)
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\cssnano-preset- 
default\node_modules\reduce-css-calc\dist\index.js:35:30
[ERROR]     at walk (D:\Projects\arif\fb-quiz\node_modules\postcss-value- 
parser\lib\walk.js:15:13)
[ERROR]     at ValueParser.walk (D:\Projects\arif\fb- 
quiz\node_modules\postcss-value-parser\lib\index.js:18:5)
[ERROR]     at exports.default (D:\Projects\arif\fb- 
quiz\node_modules\cssnano-preset-default\node_modules\reduce-css- 
calc\dist\index.js:29:51)
[ERROR]     at transformValue (D:\Projects\arif\fb- 
quiz\node_modules\cssnano-preset-default\node_modules\postcss- 
calc\dist\lib\transform.js:24:45)
[ERROR]     at exports.default (D:\Projects\arif\fb- 
quiz\node_modules\cssnano-preset-default\node_modules\postcss-
calc\dist\lib\transform.js:54:100)
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\index.js:28:52
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:144:26
[ERROR]     at Rule.each (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:110:22)
[ERROR]     at Rule.walk (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:143:21)
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:146:32
[ERROR]     at Root.each (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:110:22)
[ERROR]     at Root.walk (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:143:21)
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\index.js:25:9
[ERROR]     at initializePlugin (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\cssnano\dist\index.js:35:51)
```

**Comment by nnixaa** [comment]
Hi @arabbani, it's really hard to tell as the `Integrate Nebular.` part is quite vague as this doesn't provide us with any useful info. Could you please be more specific? Can you build a basic Angular app + Nebular without the JHipster part?

**Comment by arabbani** [comment]
Will try @nnixaa

**Comment by arabbani** [comment]
Here is a snapshot of some of nebular's css code. Something buggy here: 
![gggggggggggg](https://user-images.githubusercontent.com/13854024/45964859-87981400-c044-11e8-8ebb-cb60618d3b26.JPG)

**Comment by arabbani** [comment]
There are many error like this

**Comment by arabbani** [comment]
corporate.css, cosmic.css and default.css

**Comment by arabbani** [comment]
Is it working now!!

**Comment by yggg** [comment]
Hi @arabbani. The issue should be gone now. Before the next release, you can try to download nebular sources from GitHub and [link](https://docs.npmjs.com/cli/link) it, to verify that issue if fixed.

**Comment by arabbani** [comment]
Will do @yggg . When i expect the next version

**Comment by arabbani** [comment]
The error still exist.
![ggggggggggggggggggggggg](https://user-images.githubusercontent.com/13854024/46249977-f9f76280-c44f-11e8-9d81-fceeac28a923.JPG)

**Comment by nnixaa** [comment]
Hi @arabbani, have you npm linked the package?

**Comment by arabbani** [comment]
Yes

**Comment by arabbani** [comment]
Sure. I Will try it. But give me some time. Very busy for rest of the days of this month.
